[build]
base = "PH"
publish = "dist"
command = "npm install && npm run build"

[functions]
directory = "netlify/functions"

[build.environment]
NODE_VERSION = "20"
GEMINI_API_KEY = "placeholder"

[[plugins]]
package = "@netlify/plugin-functions-install-core"
